<a href="https://colab.research.google.com/github/Nur9702/15-dars/blob/main/birinchi_nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_list = list(range(100000)) #python list 0 ~dan 99999 -- normal
my_array = np.array(range(100000)) # numpy array (massivlar) --- vektorlashgan


In [ ]:
%time for _ in range(10): [x*2 for x in my_list] # Normal

CPU times: user 54.7 ms, sys: 2.89 ms, total: 57.6 ms
Wall time: 57.4 ms


In [ ]:
%time for _ in range(10): my_array * 2 # Vektorlashgan

CPU times: user 1.9 ms, sys: 0 ns, total: 1.9 ms
Wall time: 4.62 ms


In [ ]:
57.4/4.62

12.424242424242424

In [ ]:
import numpy as np

In [ ]:
data1 = [3.5, 5, 7.5, 8, 6, 2] #list
arr1 = np.array(data1) #array

In [ ]:
arr1

array([3.5, 5. , 7.5, 8. , 6. , 2. ])

In [ ]:
arr6 = np.arange(4, 20, 2) # 4 dan 20 gacha bo'lgan qiymatlarni 2 qadam bilan massivga joylab beradi
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr7 = np.arange(20) # 0 dan 20 gacha bo'lgan qiymatlarni 1 qadam bilan massivga joylab beradi
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
import numpy as np

In [ ]:
arr9 = np.random.randint(5, size=(2, 4)) # (2, 4) o'lchamli va max qiymati 5 gacha bo'lgan int sonlar
arr9

array([[2, 4, 0, 2],
       [4, 0, 4, 2]])

In [ ]:
arr10 = np.random.randn(2, 4) # (2, 4) o'lchamli --> elementlari (Normal dist)
arr10

array([[-0.25137831,  2.3054614 , -0.86705345, -1.10649648],
       [ 0.77695754,  1.02593511,  0.06386592,  0.50220171]])

In [ ]:
arr11 = np.empty((2,30,2))

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64) #bu float 64 massivi
arr1

array([1., 2., 3.])

In [ ]:
arr2 = np.array([1, 2, 3], dtype=np.int32) # bu int32 ma'lumotlar turiga ega massiv
arr2

array([1, 2, 3], dtype=int32)

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int32')

In [ ]:
arr = np.array([1, 2, 3, 4]) # int64
arr

array([1, 2, 3, 4])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
float_arr = arr.astype(np.float64) #arrayning typni o'zgartirish
float_arr.dtype

dtype('float64')

In [ ]:
data = np.array([3.4, 5.7, 1.8, 4]) # float64
data.dtype

dtype('float64')

In [ ]:
int_data = data.astype(np.int64)
int_data

array([3, 5, 1, 4])

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10, 100, 10)
arr[3:5]

array([40, 50])

In [ ]:
arr[3:8]

array([40, 50, 60, 70, 80])

In [ ]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [ ]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [ ]:
arr = np.arange(10, 100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
sliced_arr1 = arr[3:5].copy()
sliced_arr1[:] = 0
sliced_arr1

array([0, 0])

In [ ]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # (3, 3) o'lchamli massiv
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[1,1]

5

In [ ]:
arr2d[2,2]

9

In [ ]:
sl_arr2d =arr2d[2,1:3]
sl_arr2d

array([8, 9])

In [ ]:
# 3D array
arr3d = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8]],

                  [[ 9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr3d[0][1,2]

4

In [ ]:
arr3d[1][2,1:]

array([16, 17])

In [ ]:
arr3d[2][0, :2]

array([18, 19])

In [ ]:
import numpy as np

In [ ]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [ ]:
data = np.random.randn(7, 4)
data

array([[-0.62239926, -0.973437  ,  0.88726213, -1.11901972],
       [ 0.69450198, -0.46208985,  0.69047973, -0.6754232 ],
       [ 0.50710636,  0.63374461, -0.06836179, -0.86788591],
       [-0.64956459,  0.53249292,  1.59251909, -0.80974094],
       [ 0.75562326,  0.84787293,  0.13566905,  0.05243783],
       [ 0.51582163, -0.00758268, -1.82167017, -1.33137589],
       [ 1.27272465,  0.43046507,  0.4392575 ,  1.34729011]])

In [ ]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [ ]:
data[names=='Hasan'] # Hasanga tegishli barcha ma'lumotlarni chiqarib olish

array([[-0.62239926, -0.973437  ,  0.88726213, -1.11901972],
       [ 0.75562326,  0.84787293,  0.13566905,  0.05243783]])

In [ ]:
data[names=='Elyor']

array([[-0.64956459,  0.53249292,  1.59251909, -0.80974094],
       [ 1.27272465,  0.43046507,  0.4392575 ,  1.34729011]])

In [ ]:
data[names=='Mirzabek']

array([[ 0.50710636,  0.63374461, -0.06836179, -0.86788591]])

In [ ]:
data[names=='Hasan', 2:]

array([[ 0.88726213, -1.11901972],
       [ 0.13566905,  0.05243783]])

In [1]:
data[names=='Mirzabek', ]

NameError: name 'data' is not defined

In [2]:
import numpy as np

In [4]:
A = np.arange(6).reshape(3,2) # A massiv : Elementlari 0~6 gacha , shape (3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
A.T #

array([[0, 2, 4],
       [1, 3, 5]])

In [6]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
A.swapaxes(1, 0) #A massivning Transpose ko'rinishini beradi.

array([[0, 2, 4],
       [1, 3, 5]])

In [10]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
np.dot(A, A.T)  # AA^T hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [12]:
arr = np.arrange(10)
arr

AttributeError: module 'numpy' has no attribute 'arrange'