<a href="https://colab.research.google.com/github/Nur9702/15-dars/blob/main/Copy_of_mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [10]:
import numpy as np
np.version

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>

In [11]:
np.show_config

<function numpy.__config__.show(mode='stdout')>

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [12]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [13]:
arr1 = np.zeros(9)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [14]:
np.size(arr1)

9

In [15]:
arr1.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [16]:
x = np.arange(9)
y = np.arange(3)
y_tiled = np.tile(y, 3)
result = np.add(x, y_tiled)
print(result)

[ 0  2  4  3  5  7  6  8 10]


#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [21]:
arr3 = np.zeros(12)
arr3[6] = 1
arr3

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [22]:
arr4 = np.arange(20, 60)
arr4

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [24]:
arr4[::-1]

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [27]:
arr5 = np.arange(12, 21).reshape(3,3)
arr5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [32]:
arr6 = np.array([3, 7, 0, 0, 9, 0])
nonzero_indices = np.nonzero(arr6)
print(nonzero_indices)

(array([0, 1, 4]),)


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [38]:
arr7 = np.random.random((2,2,2))
arr7

array([[[0.52341396, 0.92706912],
        [0.86942287, 0.82095238]],

       [[0.5838907 , 0.99076015],
        [0.05442483, 0.68830675]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [39]:
arr8 = np.random.randn(9, 9)
arr8

array([[-2.75102451, -2.24609602, -1.61660432,  0.16973548, -1.75808774,
         1.33805929,  0.60668532, -0.07620685,  0.43229097],
       [-0.88562366,  0.57264318, -0.07232694, -0.28980808, -1.13006646,
        -1.68875909,  0.85920268, -0.37792997, -0.43543833],
       [ 0.93394258,  0.83758067,  0.20496862,  0.63664213,  1.20698475,
        -1.45844979, -0.49966236,  0.1085085 ,  1.47726141],
       [ 0.43458643,  3.46341509,  1.27307186,  0.67410437,  0.16829706,
        -1.17434621,  1.06512138,  0.48746111, -1.01203186],
       [ 0.31630522,  0.46058979, -0.84118394, -0.58834175, -1.3303417 ,
         0.26701043, -1.35751411, -0.35151827, -2.09350818],
       [ 0.04459633, -0.7011942 ,  0.31169288,  0.82504008,  1.04037658,
        -0.23015267, -1.82230971, -1.50747697, -1.56602965],
       [ 0.9047739 ,  0.83695488, -0.145035  , -0.03122646,  1.03159594,
        -0.32966682,  0.09773743,  0.80455792,  1.51333418],
       [ 0.35877058,  1.8844978 , -0.03538576, -1.82235994,  0

In [41]:
np.min(arr8)


-3.3991643814729917

In [42]:
np.max(arr8)

3.4634150901597756

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [43]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [48]:
a = np.random.randn(6, 3)
b = np.random.randn(3, 4)
a

array([[ 0.95933293,  0.08049433, -0.85685651],
       [ 0.7914975 ,  0.22132985, -0.09808755],
       [ 1.85347562,  0.59381046,  0.97395332],
       [ 1.35293423,  0.01954868,  0.36042862],
       [ 1.54698457, -0.39706967, -1.63383544],
       [-0.11095669, -1.1597637 ,  0.40491359]])

In [49]:
b

array([[-0.34908361,  1.43955131,  0.12176526,  0.43408996],
       [ 1.21468197, -0.05560416,  0.15600434,  0.67393299],
       [-0.95255368,  0.78062563, -0.47951702,  0.29994874]])

In [55]:

np.dot(a, b)

array([[ 0.57908943,  0.707649  ,  0.54024816,  0.21367155],
       [ 0.08598023,  1.05052475,  0.17793996,  0.46332137],
       [-0.85346992,  3.39544784, -0.14870125,  1.49689968],
       [-0.79186934,  2.22789107, -0.0050416 ,  0.70857978],
       [ 0.53397564,  0.97362857,  0.90987628, -0.08613476],
       [-1.75571283,  0.22084577, -0.3886018 , -0.70831488]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [56]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [61]:
a = [1, 2]
b = [4, 5]
a = [1, 2]
b = [4, 5]
if a > b or a >= b:
  print(False)

else:
  print(True)

True


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [62]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-62-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-62-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-62-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [70]:
arr9 = np.arange(10)
arr8 = np.arange(1, 20)
arr9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [72]:
oxshashlar = np.intersect1d(arr9, arr8)
print(oxshashlar)

[1 2 3 4 5 6 7 8 9]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [73]:
qiymat = np.random.randn(12)
qiymat

array([ 0.89151443, -0.71428961,  2.39859247, -1.26245821, -0.30706039,
       -0.82264651,  0.16293014,  0.2168469 , -0.87555868, -1.70534906,
        0.36683974,  0.83780405])

In [79]:
np.floor(qiymat)

array([ 0., -1.,  2., -2., -1., -1.,  0.,  0., -1., -2.,  0.,  0.])

In [81]:
qiymat.astype(int)

array([ 0,  0,  2, -1,  0,  0,  0,  0,  0, -1,  0,  0])

In [82]:
np.trunc(qiymat)

array([ 0., -0.,  2., -1., -0., -0.,  0.,  0., -0., -1.,  0.,  0.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [86]:
arr11 = np.arange(9).reshape(3,3)
arr11

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [91]:
arr11 = np.random.randn(11)
arr11

array([-1.95811722, -1.95723444, -1.2470809 , -1.23396287,  1.3160082 ,
       -1.51187588, -0.02252234,  0.07233755,  0.24836992,  0.04362612,
        0.34187576])

In [92]:
np.sort(arr11)

array([-1.95811722, -1.95723444, -1.51187588, -1.2470809 , -1.23396287,
       -0.02252234,  0.04362612,  0.07233755,  0.24836992,  0.34187576,
        1.3160082 ])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [93]:
arr11 = np.random.randn(11)
arr12 = np.random.randn(0, 15)

In [94]:
np.array_equal(arr11, arr12)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [96]:
a = np.random.randn(6, 3)
b = np.random.randn(3, 4)

In [97]:
np.dot(a, b)

array([[ 0.55869241,  0.19345852,  1.30986525,  1.27211073],
       [ 0.35852204, -0.03981787,  0.18663996,  0.53206826],
       [ 0.72470668,  3.09005748,  2.11415722,  1.99112679],
       [ 0.93976829,  0.33150532,  1.96675719,  2.04080908],
       [ 0.83428795,  2.0784338 ,  0.71651602,  1.48412158],
       [ 0.11447231,  0.40866006, -1.48074204, -0.45229913]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [99]:
a = np.random.randn(5)
a

array([-3.18212817e-01, -2.07736530e-01,  1.69504599e+00,  5.91759233e-04,
       -9.34610453e-02])

In [109]:
np.argmax(a) == 0
a

array([-3.18212817e-01, -2.07736530e-01,  1.69504599e+00,  5.91759233e-04,
       -9.34610453e-02])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [111]:
import numpy as np
ertaga = np.datetime64('2025-11-01')
kecha = np.datetime64('2025-09-01')
ertaga

numpy.datetime64('2025-11-01')

In [112]:
kecha

numpy.datetime64('2025-09-01')

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [114]:
start_date = np.datetime64('2016-01-01')
end_date = np.datetime64('2016-02-01')

yanvar_2016 = np.arange(start_date, end_date, dtype='datetime64[D]')

print(yanvar_2016)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [115]:
a

array([-3.18212817e-01, -2.07736530e-01,  1.69504599e+00,  5.91759233e-04,
       -9.34610453e-02])

In [116]:
musbat = np.floor(a>0)
musbat

array([0., 0., 1., 1., 0.], dtype=float16)

In [117]:
musbat = np.trunc(a<0)
musbat

array([1., 1., 0., 0., 1.], dtype=float16)

In [119]:
a.astype(int)

array([0, 0, 1, 0, 0])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [124]:
a = [2,3,4]
b = [5,6,7]
c = [8,9,9]
qiymat = np.sum([a,b,c])
np.add.reduce(qiymat)
qiymat


53

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [125]:
abb = [1, 2, 3, 4, 5]
abb

[1, 2, 3, 4, 5]

In [132]:
abb_np = np.array(abb)
result = np.add(abb_np[0], 3)
result

4

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [133]:
a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]

In [138]:
!pip install numpy --upgrade
import numpy as np
from numpy.lib import stride_tricks # Import stride_tricks from numpy.lib

a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
n = 4

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 84.3 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.2.1 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.1 which is incompatible.
langchain 0.3.14 requires numpy<2,>=1.22.4; python_version < "3.12", but you have numpy 2.2.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.1 which is incompatible.
pytensor 2.26.4 requires numpy<2,>=1.17.0, but you have numpy 2.2.1 which is incompatible.
tensorflow 2.17.1 requires numpy<

In [142]:
b = stride_tricks.as_strided(a)
b


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [146]:
b = np.random.randn(9)
c = np.random.randn(15)
d = np.intersect1d(b, c)
print(oxshashlar)

[1 2 3 4 5 6 7 8 9]


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`